### PR TITLE
Remove many deprecated pylint options

### PR DESCRIPTION
**Pull request by hmaarrfk**
These were mostly useful for the python2->python3 transition

https://github.com/PyCQA/pylint/pull/4942

**Relevant issues/PRs:**

### CODE REVIEW

**Comment by leouieda** [comment]
@hmaarrfk thanks for this! Let me know when this is ready for a review. There are quite a few changes here but I’m assuming they’re related to making pylint pass, right?

**Comment by hmaarrfk** [comment]
@leouieda i think this is ready. it is likely best to review each commit one at a time.

They are each organized in a thematic manner and it makes it more clear what the improvement is.

There are some (such as the timeout) that may be worth more discussion.

**Comment by hmaarrfk** [comment]
Not specifying the timeout really causes requests to hang.... it might have been a linting recommendation, but I've experienced this alot in our "web connected" application.

If you want to support offline, you must specify a timeout mostly everywhere.

**Comment by leouieda** [comment]
Just waiting on #373 to make sure everything is running properly here before merging.

**Comment by leouieda** [comment]
Finally merging this! Thanks for all your hard work @hmaarrfk 🫶

**Comment by hmaarrfk** [comment]
no problem!

**Pull request merged**
