### PR TITLE
Redesign the front page of the docs

### PR DESCRIPTION
**Pull request by leouieda**
Remove the wall of text and make clear boxes for getting started, asking for help, API reference, and citing. Include the full table of contents underneath to help with navigation. Move the text about different use cases to a "Why Pooch?" page. Introduces the `sphinx-panels` extension to use cards, columns, and tabs.

**Preview of the built docs**: https://www.leouieda.com/docs-previews/pooch/238/

**Reminders**:

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst` and the base `__init__.py` file for the package.
- [ ] Write detailed docstrings for all functions/classes/methods. It often helps to design better code if you write the docstrings first.
- [ ] If adding new functionality, add an example to the docstring, gallery, and/or tutorials.
- [ ] Add your full name, affiliation, and [ORCID](https://orcid.org) (optional) to the `AUTHORS.md` file (if you haven't already) in case you'd like to be listed as an author on the [Zenodo](https://zenodo.org/communities/fatiando) archive of the next release.

### CODE REVIEW

**Comment by leouieda** [comment]
@prisae @aguspesce @santisoler what do you think?

**Review by prisae — APPROVED** [review]
I like it, I think it makes it easier to get started. Also the new tabs on the About and Installing sections look neat!

**Comment by santisoler** [comment]
This looks awesome! I ❤️ the tabs! And the cards in the front page looks amazing.

The only thing I would change is the color of the text inside the buttons when hovering. Currently, when hovering over the buttons, the text inside them is shown in the same original blue color, while the button itself fills with another tone of blue, drastically lowering the contrast of the text and its background. Besides the aesthetics, I think we should change that to improve accessibility.

**Comment by leouieda** [comment]
Thanks @santisoler @prisae! That was an easy fix. Merging this in!

**Pull request merged**
