### PR TITLE
Add Hugo van Kemenade (hugovk) to author list

### PR DESCRIPTION
**Pull request by hugovk**
For [PR 💯](https://github.com/fatiando/pooch/pull/100)

### CODE REVIEW

**Comment by leouieda** [comment]
@hugovk we've been keeping the list in alphabetical order by last name, so you should probably be first :slightly_smiling_face:

**Comment by hugovk** [comment]
It depends on which country's surname sort order you use! But this being Python, I guess we can follow Guido's lead :)

https://github.com/python/cpython/blob/dfe726b1ace03f206f45253b93ed7610473ae20f/Misc/ACKS#L1416

Updated!

**Comment by leouieda** [comment]
@hugovk Guido knows best :) Thanks!

**Comment by leouieda** [comment]
> Dutch sort

:rofl:

**Comment by hugovk** [comment]
🇳🇱

**Pull request merged**
