### PR TITLE
Speed up import type (0.05 s to 0.02 s) by lazy loading requests

### PR DESCRIPTION
**Pull request by hmaarrfk**
I'm proposing lazy loading requests since it adds a bit of import of.

Usually, I think that pooch is used as an import addon but not as a core feature. As such it is a little silly to expand the import time by alot. While small, it is not insignificant.

Thank you for considering

Current
image

Proposed
image

### CODE REVIEW

**Comment by leouieda** [comment]
@hmaarrfk sorry for the long delay on this. I've been away from OSS work for a while and am only slowly returning now. We'll get to this PR as soon as possible. Thanks for going thought the trouble and being patient 🙂

**Comment by leouieda** [comment]
@hmaarrfk will merge this ASAP. We're having a failure on the Mac builds for Python 3.7 because the GitHub `setup-python` action is trying to compile Python and failing to link to libbz2...

**Comment by hmaarrfk** [comment]
No issues.  Take your time.

**Comment by leouieda** [comment]
Thanks @hmaarrfk! Finally got some time to sort this out. Thank you your help!

**Pull request merged**
